### ISSUE TITLE
Number of agents/people in AMASS dataset

### ISSUE THREAD

**Issue by WBMao** [evendrow/somoformer#2]
Hi @evendrow,

I have a question about the number of agents in AMASS dataset. The number of interacting agents in 3DPW is 2, while this number in AMASS is 1, indicating 3DPW is a multi-person dataset and AMASS is single-person. So I am wondering, do you generate a synthesis multi-person dataset for AMASS or not?

Please correct me if my understanding is wrong.

Thanks,
Weibo.

**Comment by evendrow** [comment]
Hi Weibo,

Thanks for the question! As we mention in our paper, we do synthesize additional multi-person data using AMASS (specifically, the CMU subset), although other  single-person subsets (BMLMovie, BMLrub) are unmodified. We're currently working on releasing code for performing this data synthesis. 

During training, we use both multi-person and single-person data, which is possible by padding sequences and using a padding mask, similar to how language models pad sequences with fewer word tokens. 

Thanks,
Eddie
